In [1]:
import numpy as np

In [2]:
np.__version__

'2.2.3'

## Create & Readb

#### 1D Array

In [3]:
array1 = np.array([1, 2, 3, 4, 5])
array1

array([1, 2, 3, 4, 5])

In [4]:
type(array1)

numpy.ndarray

In [5]:
array1.shape # (row, col)

(5,)

In [6]:
# Quel type d'éléments
array1.dtype

dtype('int64')

In [7]:
# Combien de dimmension à le tableau
array1.ndim

1

In [8]:
# Nombre d'eléments
array1.size

5

#### 2D Array

In [10]:
array2 = np.array([[1, 2, 3], [4, 5, 6]])
array2

array([[1, 2, 3],
       [4, 5, 6]])

In [11]:
array2.ndim

2

In [12]:
array2.shape # (row, col)

(2, 3)

In [13]:
array2.size

6

#### 3D Array

In [17]:
array3 = np.array([[[1, 2, 3], [4, 5, 6]], [[3, 4, 5], [5, 8, 7]], [[9, 2, 55], [48, 5, 16]]])
array3

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 3,  4,  5],
        [ 5,  8,  7]],

       [[ 9,  2, 55],
        [48,  5, 16]]])

In [18]:
array3.ndim

3

In [19]:
array3.shape

(3, 2, 3)

In [23]:
array3.size

18

In [28]:
array3[0]

array([[1, 2, 3],
       [4, 5, 6]])

In [33]:
array3[1][1][1]

np.int64(8)

In [34]:
array3[0:2]

array([[[1, 2, 3],
        [4, 5, 6]],

       [[3, 4, 5],
        [5, 8, 7]]])

In [35]:
array3[-1]

array([[ 9,  2, 55],
       [48,  5, 16]])

In [36]:
array3[1][0][1]

np.int64(4)

In [37]:
# ou 2ème solution
array3[1, 0, 1]

np.int64(4)

## Create random array

In [21]:
randomArr = np.random.rand(3, 2, 3)
randomArr

array([[[0.24366228, 0.43617831, 0.03012975],
        [0.34439272, 0.59051346, 0.84045601]],

       [[0.44339108, 0.10347768, 0.371114  ],
        [0.72605323, 0.55190912, 0.61499523]],

       [[0.22895447, 0.83039741, 0.41382168],
        [0.55444973, 0.20636839, 0.26595188]]])

In [22]:
randomArr.dtype

dtype('float64')

In [24]:
zeroes = np.zeros((3, 2, 3))
zeroes

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [25]:
zeroes.ndim

3

In [26]:
full = np.full((3, 2, 3), 9)
full

array([[[9, 9, 9],
        [9, 9, 9]],

       [[9, 9, 9],
        [9, 9, 9]],

       [[9, 9, 9],
        [9, 9, 9]]])

In [27]:
ones = np.ones((3, 4, 3))
ones

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

## Update & Delete

In [39]:
a1 = np.random.rand(2, 3, 2)
a2 = np.random.rand(2, 3, 2)
a1

array([[[0.07926308, 0.15749678],
        [0.5956594 , 0.26584336],
        [0.33318993, 0.84719862]],

       [[0.4016161 , 0.6347078 ],
        [0.59820686, 0.14815273],
        [0.15981611, 0.62397407]]])

In [40]:
a2

array([[[0.32608928, 0.85410465],
        [0.14992284, 0.39791744],
        [0.98639352, 0.43972187]],

       [[0.31630408, 0.79160463],
        [0.96489834, 0.45649423],
        [0.62796182, 0.65179302]]])

In [41]:
np.add(a1, a2)

array([[[0.40535236, 1.01160143],
        [0.74558224, 0.6637608 ],
        [1.31958345, 1.28692049]],

       [[0.71792018, 1.42631242],
        [1.5631052 , 0.60464697],
        [0.78777794, 1.27576709]]])

In [43]:
np.subtract(a1, a2)

array([[[-0.24682619, -0.69660787],
        [ 0.44573655, -0.13207409],
        [-0.65320358,  0.40747675]],

       [[ 0.08531201, -0.15689683],
        [-0.36669148, -0.3083415 ],
        [-0.46814571, -0.02781896]]])

In [44]:
np.divide(a1, a2)

array([[[0.24307173, 0.18439986],
        [3.97310631, 0.66808671],
        [0.33778601, 1.92666928]],

       [[1.26971517, 0.801799  ],
        [0.6199688 , 0.32454459],
        [0.25449973, 0.95731934]]])

In [45]:
np.multiply(a1, a2)

array([[[0.02584684, 0.13451873],
        [0.08930295, 0.10578371],
        [0.32865639, 0.37253176]],

       [[0.12703281, 0.50243763],
        [0.57720881, 0.06763087],
        [0.10035842, 0.40670194]]])

In [47]:
sqrt = np.sqrt(25)
abs = np.abs(-2)
power = np.power(2, 8)
log = np.log(25)
mins = np.min(a1)
maxs = np.max(a2)
sqrt


np.float64(0.9863935165471074)

In [48]:
sqrt

np.float64(5.0)

In [49]:
abs

np.int64(2)

In [50]:
power

np.int64(256)

In [51]:
log

np.float64(3.2188758248682006)

In [52]:
mins

np.float64(0.07926308282741334)

In [53]:
maxs

np.float64(0.9863935165471074)

## update

In [54]:
array3

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 3,  4,  5],
        [ 5,  8,  7]],

       [[ 9,  2, 55],
        [48,  5, 16]]])

In [59]:
array3[0, 0, 2] = 500
array3

array([[[  1, 500, 500],
        [  4,   5,   6]],

       [[  3,   4,   5],
        [  5,   8,   7]],

       [[  9,   2,  55],
        [ 48,   5,  16]]])

In [60]:
array3.sort()
array3

array([[[  1, 500, 500],
        [  4,   5,   6]],

       [[  3,   4,   5],
        [  5,   7,   8]],

       [[  2,   9,  55],
        [  5,  16,  48]]])

In [61]:
# Reshape
array3.shape

(3, 2, 3)

In [63]:
array3_reshape = array3.reshape((2, 3, 3)) # équivalent = array3.reshape((2, 3, -1))
array3_reshape

array([[[  1, 500, 500],
        [  4,   5,   6],
        [  3,   4,   5]],

       [[  5,   7,   8],
        [  2,   9,  55],
        [  5,  16,  48]]])

#### Appending & Inserting

In [64]:
zeroes

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [65]:
# Create a new array
new_array = np.ones((3, 2, 3))
new_array

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

In [66]:
appd = np.append(zeroes, new_array, axis=0) # axis 0 = row, axis 1 = colonne
appd

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

In [67]:
# Insert
zeroes

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [68]:
new_array

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

In [71]:
inserted_array = np.insert(zeroes, 1, new_array, axis=0)
inserted_array

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [72]:
inserted_array.shape

(6, 2, 3)

## Delete

In [74]:
array4 = np.random.rand(3, 2, 3)
array4

array([[[0.34342775, 0.75524631, 0.43323106],
        [0.75825317, 0.38022069, 0.67712666]],

       [[0.52420886, 0.81244873, 0.30183077],
        [0.02606832, 0.75300917, 0.06253338]],

       [[0.90363536, 0.28255453, 0.47262685],
        [0.85674355, 0.29277863, 0.47633573]]])

In [77]:
# delete the array
array5 = np.delete(array4, 0, axis=1)
array5

array([[[0.75825317, 0.38022069, 0.67712666]],

       [[0.02606832, 0.75300917, 0.06253338]],

       [[0.85674355, 0.29277863, 0.47633573]]])

In [79]:
np.save("new_array", array5)

In [81]:
np.load("new_array.npy")

array([[[0.75825317, 0.38022069, 0.67712666]],

       [[0.02606832, 0.75300917, 0.06253338]],

       [[0.85674355, 0.29277863, 0.47633573]]])